time_step = 1e-4

[protocol]
pre_stimulus_period = 0.5  # *1s
post_stimulus_period = 0.5
stimulus_duration = 0.5

[initial_conditions]
membrane_potential = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
adaptation = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]