time_step = 1e-3

[protocol]
pre_stimulus_period = 0.5  # *10s
post_stimulus_period = 0.5
stimulus_duration = 0.5

[initial_conditions]
membrane_potential = [
    -1.5554, 8.9735, 12.0712, 12.5040,
    -5.2554, 10.4650, -30.8225, 12.6189
]
# membrane_potential = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
adaptation = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]